### ISSUE TITLE
Test allowedRoles

### ISSUE THREAD

**Issue by gentlementlegen** [Meniole/command-start-stop#55]
Allowed roles:
```
          requiredLabelsToStart:
            - name: "Priority: 1 (Normal)"
              allowedRoles: ['collaborator']                
            - name: "Priority: 2 (Medium)"
              allowedRoles: ['contributor']            
            - name: "Priority: 3 (High)"
              allowedRoles: ['collaborator', 'contributor']
            - name: "Priority: 4 (Urgent)"
              allowedRoles: ['collaborator']
            - name: "Priority: 5 (Emergency)"
```
